"""Feature-parity tests: the contract that keeps Python training and C++
serving honest with each other.

- Golden vectors are generated by the reference packer (scripts: see
  fixtures/golden/README note inside the JSON) and committed.
- test_cpp_parity activates automatically once the C++ CLI is discoverable:
  ACTWARDEN_CLI env var, then runtime/build/actwarden, then PATH.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from actwarden.features import FeaturePacker, feature_names, load_spec
from actwarden.replay import replay_trace
from actwarden.traces import group_by_session, read_jsonl

ACTWARDEN_DIR = Path(__file__).resolve().parents[2]
SPEC = ACTWARDEN_DIR / "feature_spec" / "v1.json"
TRACE = ACTWARDEN_DIR / "fixtures" / "traces" / "runaway_loop.jsonl"
GOLDEN = ACTWARDEN_DIR / "fixtures" / "golden" / "runaway_loop.features.json"
CPP_CLI = Path(
    os.environ.get(
        "ACTWARDEN_CLI", ACTWARDEN_DIR / "runtime" / "build" / "actwarden"
    )
)

TOL = 1e-6


def test_spec_is_valid():
    spec = load_spec(SPEC)
    assert len(spec["features"]) == 16
    assert [h["name"] for h in spec["risk_heads"]] == [
        "loop_risk",
        "cost_risk",
        "tool_misuse_risk",
        "dead_end_risk",
    ]


def test_reference_packer_matches_golden():
    spec = load_spec(SPEC)
    packer = FeaturePacker(spec)
    sessions = group_by_session(read_jsonl(TRACE))
    golden = json.loads(GOLDEN.read_text())
    assert golden["spec_version"] == spec["spec_version"]
    assert golden["feature_names"] == feature_names(spec)
    for session_id, expected in golden["sessions"].items():
        got = packer.pack(sessions[session_id])
        assert len(got) == len(expected)
        for i, (g, e) in enumerate(zip(got, expected)):
            assert abs(g - e) <= TOL, f"{session_id} feature[{i}] {g} != {e}"


def test_runaway_loop_looks_loopy():
    """Sanity: the fixture must actually exhibit the pathology it claims."""
    spec = load_spec(SPEC)
    feats = FeaturePacker(spec).pack(
        group_by_session(read_jsonl(TRACE))["sess-01"]
    )
    idx = {f["name"]: f["index"] for f in spec["features"]}
    assert feats[idx["tool_ngram_repeat_ratio"]] >= 0.5
    assert feats[idx["tool_entropy_norm"]] == 0.0
    assert feats[idx["stagnation_norm"]] >= 0.8
    assert feats[idx["error_rate"]] == 0.0


def test_replay_smoke():
    report = replay_trace(TRACE, SPEC)
    assert len(report.steps) == 15
    assert set(report.action_counts) <= {
        "continue",
        "reduce_budget",
        "switch_model",
        "require_approval",
        "block_tool",
        "escalate",
    }
    assert 0.0 <= report.flip_rate <= 1.0


@pytest.mark.skipif(
    not (CPP_CLI.exists() or shutil.which("actwarden")),
    reason="C++ runtime not built; run cmake in actwarden/runtime first",
)
def test_cpp_parity():
    """C++ packer must reproduce the reference features on the fixture."""
    cli = str(CPP_CLI if CPP_CLI.exists() else shutil.which("actwarden"))
    out = subprocess.run(
        [cli, "--trace", str(TRACE), "--spec", str(SPEC), "--emit-features"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    # CLI emits one JSON object per step; compare the final window per session.
    last_by_session: dict[str, list[float]] = {}
    for line in out.splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        last_by_session[rec["session_id"]] = rec["features"]

    spec = load_spec(SPEC)
    packer = FeaturePacker(spec)
    for session_id, spans in group_by_session(read_jsonl(TRACE)).items():
        expected = packer.pack(spans)
        got = last_by_session[session_id]
        for i, (g, e) in enumerate(zip(got, expected)):
            assert abs(g - e) <= TOL, f"{session_id} feature[{i}] {g} != {e}"
